#pragma once

#include <irrlicht/IParticleSystemFactory.h>
#include <irrlicht/IParticleBasicInitializer.h>
#include <irrlicht/IParticleAnimatedMeshInitializer.h>
#include <irrlicht/IParticleBoxInitializer.h>
#include <irrlicht/IParticleCylinderInitializer.h>
#include <irrlicht/IParticleDirectionInitializer.h>
#include <irrlicht/IParticleMeshInitializer.h>
#include <irrlicht/IParticleRingInitializer.h>
#include <irrlicht/IParticleSphereInitializer.h>
#include <irrlicht/IParticleCompositeInitializer.h>
#include <irrlicht/IParticleAttractionAffector.h>
#include <irrlicht/IParticleFadeOutAffector.h>
#include <irrlicht/IParticleForceAffector.h>
#include <irrlicht/IParticleRotationAffector.h>
#include <irrlicht/IParticleEmitter.h>
#include <irrlicht/IParticlePointRenderer.h>
#include <irrlicht/IParticleQuadRenderer.h>
#include <irrlicht/IParticleSystemSceneNode.h>
#include <irrlicht/IParticleSystemFactory.h>