package.path = package.path 
.. ";Assets/Script/?.lua"
.. ";Assets/Script/Action/?.lua" 
.. ";Assets/Script/Effect/?.lua"
.. ";Assets/Script/Utils/?.lua"
.. ";Assets/Script/Save/?"
.. ";Assets/Script/Database/?.lua"
.. ";Assets/Script/Strategy/?.lua"
.. ";Assets/Script/Component/?.lua"
.. ";Assets/Script/IO/?.lua"
.. ";Assets/Script/Manager/?.lua"
.. ";Assets/Script/Ease/?.lua"
.. ";Assets/Script/route/?.lua"
.. ";Assets/Script/Barrier/?.lua"
.. ";Assets/Script/HighAction/?.lua"
.. ";Assets/Script/MapElement/?.lua"
.. ";Assets/Script/Warrior/?.lua"
